### PR TITLE
Fix compiling the manual

### PR DESCRIPTION
**Pull request by hmenke**
These are the fixes discovered in the process of setting up the CI, which are necessary to build the manual with the current TeX Live.

### CODE REVIEW

**Comment by hmenke** [comment]
@cfeuersaenger This is the part of #392 without the CI infrastructure.

**Comment by cfeuersaenger** [comment]
Thanks! I will review the 133aa0b and 7d1895 in the next days (I cannot judge their impact from the diff and I would like to make a pgfplots release soon - without destabilizing unexpected parts of the codebase).

I have no problem with pure CI infrastructure items as they do not affect the package as such, i.e. I am fine to merge the  CI parts immediately.

**Comment by hmenke** [comment]
The only part of the CI that's done is the manual. All tests are still failing, partly due to them actually failing and partly due to the setup not working correctly, yet.

**Comment by hmenke** [comment]
@cfeuersaenger ping

**Pull request merged**
